Fixes #143, return_surface and return_midpoint
p-j-smith/lipyphilic pull request #146
Opened 2024-12-09 16:40 UTC by RubenChM

Changes made in this Pull Request:
 - Fixes [#143](https://github.com/p-j-smith/lipyphilic/issues/143)
 - [Add return_midpoint](https://github.com/p-j-smith/lipyphilic/commit/2882db5c6708ccb5a8bb3e0ed89af867c421dfdf) to `Zpositions` similar to `return_surface` from `MembThickness`.
 - [Fix error with return_surface=True and n_bins=1](https://github.com/p-j-smith/lipyphilic/commit/6da77c181fda4f2c5151f8ef4c080530a83f9e5a)

PR Checklist
------------
 - [x] Tests added and passing? Except `test_memb_thickness.py::TestMembThicknessUndulating::test_nbins200_no_interpolation`
 - [x] Docs added and building?
 - [ ] CHANGELOG updated?
 - [x] AUTHORS updated if necessary?
 - [x] Issue raised and referenced?

2025-02-24 21:20 UTC, p-j-smith requested changes
Thanks for this @RubenChM ! And apologies for the slow review.

A few minor suggestions, plus a test for the new behaviour (`return_midpoint`) is needed

2025-02-24 21:20 UTC, p-j-smith commented on CONTRIBUTING.rst
> +    source $HOME/.cargo/env
probably worth linking [here](https://www.rust-lang.org/tools/install) instead in case someone is using Windows

2025-02-24 21:20 UTC, p-j-smith commented on src/lipyphilic/analysis/memb_thickness.py
> +            default is False.
Thanks for spotting this. I know it wasn't added in this PR, but could you store the result in `self.results.memb_thickness_grid` instead, and add a property `self.memb_thickness_grid` that returns this (just so that we're using the MDAnalysis `Results` class whilst also not breaking existing code)

2025-02-24 21:20 UTC, p-j-smith commented on src/lipyphilic/analysis/z_positions.py
> +                fill_value=np.NaN)
similarly here, the midpoint should be stored in `self.results.memb_midpoint` and a property `self.memb_midpoint` would return the midpoint stored in the `Results` class

2025-02-24 21:20 UTC, p-j-smith commented on src/lipyphilic/analysis/z_positions.py
> +            self.memb_midpoint[self._frame_index] = memb_midpoint_xy.statistic if self.n_bins > 1 else memb_midpoint_xy.statistic[0, 0]
please add a test to check to correct midpoints are returned

2025-03-13 15:14 UTC, RubenChM commented
I added the suggested changes and test. The test should be passing or at least they did while running `tox` locally

2025-03-13 15:23 UTC, p-j-smith approved these changes
thanks @RubenChM !

2025-03-13 15:25 UTC, merged